spring:
  datasource:
    generate-unique-name: false
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html


    